# Generate-Entities.ps1
# Cleans the AutoGeneratedEntities folder and regenerates entity classes from a Dataverse environment.
#
# CONNECTION:
#   This script relies on the PAC CLI active auth profile.
#   Before running this script for the first time, authenticate using:
#       pac auth create --url https://<your-org>.crm.dynamics.com
#   To see your current auth profile:
#       pac auth list
#   To switch profiles:
#       pac auth select --index <number>
# USAGE:
#   1. Update the $entities array with the logical names of the entities you want to generate.
#   2. Run the script in PowerShell.

$autoGenPath = $PSScriptRoot

# -------------------------------------------------------
# Entities to generate - add or remove as needed
# -------------------------------------------------------
$entities = @(
    "account"
    "contact"
)
# -------------------------------------------------------

$entityFilter = $entities -join ";"

Write-Host "Cleaning AutoGeneratedEntities folder..." -ForegroundColor Yellow
Get-ChildItem -Path $autoGenPath -Filter "*.cs" -Recurse | Remove-Item -Force
Write-Host "Folder cleaned." -ForegroundColor Green

Write-Host "Generating entities from Dataverse..." -ForegroundColor Yellow
pac modelbuilder build `
    --outdirectory $autoGenPath `
    --namespace "DynamicsFramework.Entities.Generated" `
    --entitynamesfilter $entityFilter `
    --serviceContextName "CrmServiceContext" `
    --suppressINotifyPattern `
    --emitfieldsclasses `
    --language CS `
    --suppressGeneratedCodeAttribute `
    --generateGlobalOptionSets

Write-Host "Generation complete." -ForegroundColor Green
